### ISSUE TITLE
Low image quality for jpg

### ISSUE THREAD

**Issue by bertheyman** [ramonfritsch/gulp-unretina#2]
When I run your (very useful) gulp extension, the quality for resized jpg image is pretty low. For similar png images, everything works fine.
Tried both without options and with quality: 1.

> gulp.task('resize', function () {
>  gulp.src('public/images/*@2x.{jpg,png}')
>    .pipe(unretina({
>      quality: 1 // should be default, added just to be sure
>    }))
>    .pipe(gulp.dest('public/images/'));
> });

**Comment by bertheyman** [comment]
Workaround for people with the same problem:
I used [Gulp image resize](https://www.npmjs.com/package/gulp-image-resize) with these settings to achieve the desired effect. (using imageMagick instead of default graphicsmagick)

> gulp.task('resize', function () {
>  gulp.src('source/*.{jpg,png}')
>    .pipe(imageResize({
>      width : "50%",
>      height : "50%",
>      upscale : false,
>      imageMagick : true
>    }))
>    .pipe(gulp.dest('dest'));
> });

**Comment by ramonfritsch** [comment]
Issue was fixed on last commit
